name: ci

on:
  push:
    branches:
      - "main"
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - alpine-nor
          - devcontainer-base

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}            
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha
            type=edge,branch=main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.image }}/.
          platforms: linux/amd64,linux/arm64
          build-args: |
            GIT_NAME=${{ vars.GIT_NAME }}
            GIT_EMAIL=${{ vars.GIT_EMAIL }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

